- name: configure ip pools
  kubernetes.core.k8s:
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "{{ item.name }}"
        namespace: metallb-system
      spec:
        addresses: 
          - "{{ item.pool }}"
  with_items: "{{ ip_pools }}"

- name: configure layer2 mode for external announcement
  kubernetes.core.k8s:
    definition: 
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-advertise
        namespace: metallb-system
      spec:
        ipAddressPools:
        - "{{ item.name }}"
  with_items: "{{ ip_pools }}"
